name: Create Release with 7z Archive

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'
      description:
        description: 'Release description'
        required: false
        default: 'Automatic release with build archive'

jobs:
  release:
    name: Create Release with Archive
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create 7z archive
      uses: edgarrc/action-7z@v1
      with:
        args: 7z a -t7z -mx=9 build-${{ github.event.inputs.version }}.7z ./build/
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.version }}
        name: Release ${{ github.event.inputs.version }}
        body: ${{ github.event.inputs.description }}
        files: build-${{ github.event.inputs.version }}.7z
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
