name: Create Release with 7z Archive

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag'
        required: true
        default: 'v1.7.9-auto-release'
      description:
        description: 'Release description'
        required: false
        default: 'Automatic release'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Prepare fomod structure
      run: |
        mkdir -p fomod
        rsync -av \
          --exclude='.git' \
          --exclude='.github' \
          --exclude='.gitattributes' \
          --exclude='*.7z' \
          --exclude='README.md' \
          --exclude='fomod' \
          ./* fomod/
        
        echo "📁 Содержимое папки fomod:"
        ls -la fomod/
      
    - name: Create 7z archive
      uses: edgarrc/action-7z@v1
      with:
        args: 7z a -t7z -mx=9 fatal-error-${{ github.event.inputs.version }}.7z ./fomod/
        
    - name: Clean up
      run: rm -rf fomod
      
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.version }}
        name: Release ${{ github.event.inputs.version }}
        body: |
          ${{ github.event.inputs.description }}
        files: project-${{ github.event.inputs.version }}.7z
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
